g2features = function() c("NHLBIkey", "HUPfield", "LastCurationDate", "CreationDate", 
"SNPid.dbSNP134.", "chr.hg19.", "pos.hg19.", "PMID", "SNPid.in.paper.", 
"LocationWithinPaper", "Pvalue", "Phenotype", "PaperPhenotypeDescription", 
"PaperPhenotypeCategories", "DatePub", "InNHGRIcat.as.of.3.31.12.", 
"Journal", "Title", "IncludesMale.Female.Only.Analyses", "Exclusively.Male.Female", 
"Initial.Sample.Description", "Replication.Sample.Description", 
"Platform..SNPs.passing.QC.", "GWASancestryDescription", "TotalSamples.discovery.replication.", 
"TotalDiscoverySamples", "European.Discovery", "African.Discovery", 
"East.Asian.Discovery", "Indian.South.Asian.Discovery", "Hispanic.Discovery", 
"Native.Discovery", "Micronesian.Discovery", "Arab.ME.Discovery", 
"Mixed.Discovery", "Unspecified.Discovery", "Filipino.Discovery", 
"Indonesian.Discovery", "Total.replication.samples", "European.Replication", 
"African.Replication", "East.Asian.Replication", "Indian.South.Asian.Replication", 
"Hispanic.Replication", "Native.Replication", "Micronesian.Replication", 
"Arab.ME.Replication", "Mixed.Replication", "Unspecified.Replication", 
"Filipino.Replication", "Indonesian.Replication", "InGene", "NearestGene", 
"InLincRNA", "InMiRNA", "InMiRNABS", "dbSNPfxn", "dbSNPMAF", 
"dbSNPalleles.het.se", "dbSNPvalidation", "dbSNPClinStatus", 
"ORegAnno", "ConservPredTFBS", "HumanEnhancer", "RNAedit", "PolyPhen2", 
"SIFT", "LS.SNP", "UniProt", "EqtlMethMetabStudy")
